openapi: '3.0.3'
security:
  - BearerAuth: [accessToken, serverToken]

info:
  title: LRT users API
  version: '1.0'
servers:
  - url: https://lrt.lt/api/v1
paths:
  /users/{id}:
    get:
      summary: Get User by ID
      description: Retrieve a user by their ID
      security:
        - BearerAuth: [accessToken]
      tags: [Users]

      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
          description: ID of the user to retrieve
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto' # Reference the User schema

  /user/set-onboarding-completed:
    post:
      summary: Set Onboarding Completed
      description: Mark the user's onboarding as completed
      security:
        - BearerAuth: [accessToken]
      tags: [Users]

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto' # Reference the User schema\

  /user/articles:
    post:
      summary: Save User Article
      description: Save an article for a user
      security:
        - BearerAuth: [accessToken]
      tags: [Articles]

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSavedArticle' # Reference the UserSavedArticle schema

      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSavedArticle' # Reference the UserSavedArticle schema
    get:
      summary: Get User Saved Articles
      description: Retrieve all saved articles for a user
      security:
        - BearerAuth: [accessToken]
      tags: [Articles]

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserSavedArticle' # Reference the UserSavedArticle schema

    delete:
      summary: Remove User Saved Article
      description: Remove a saved article for a user
      security:
        - BearerAuth: [accessToken]
      tags: [Articles]

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteArticleDto' # Reference the UserSavedArticle schema

      responses:
        '204':
          description: No Content

  /user/history:
    post:
      summary: Save User Article History
      description: Save the history of an article for a user
      security:
        - BearerAuth: [accessToken]
      tags: [ArticleHistory]

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSavedArticle' # Reference the UserSavedArticle schema

      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSavedArticle' # Reference the UserSavedArticle schema

    get:
      summary: Get User Article History
      description: Retrieve the history of articles for a user
      security:
        - BearerAuth: []
      tags: [ArticleHistory]

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserSavedArticle' # Reference the UserSavedArticle schema

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    UserDto:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          nullable: true
        createdAt:
          type: string
          readOnly: true
        onboardingCompleted:
          type: boolean
          default: false
          readOnly: true
    UserSavedArticle:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        userId:
          type: integer
          readOnly: true
        articleId:
          type: integer
        createdAt:
          type: string
          readOnly: true
    DeleteArticleDto:
      type: object
      properties:
        articleId:
          type: integer
