//Home
export const FETCH_HOME = 'FETCH_HOME';
export const API_HOME_RESULT = 'API_HOME_RESULT';
export const API_HOME_ERROR = 'API_HOME_ERROR';

//Mediateka
export const FETCH_MEDIATEKA = 'FETCH_MEDIATEKA';
export const API_MEDIATEKA_RESULT = 'API_MEDIATEKA_RESULT';
export const API_MEDIATEKA_ERROR = 'API_MEDIATEKA_ERROR';

//Audioteka
export const FETCH_AUDIOTEKA = 'FETCH_AUDIOTEKA';
export const API_AUDIOTEKA_RESULT = 'API_AUDIOTEKA_RESULT';
export const API_AUDIOTEKA_ERROR = 'API_AUDIOTEKA_ERROR';

//Categories
export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const REFRESH_CATEGORY = 'REFRESH_CATEGORY';
export const API_CATEGORY_RESULT = 'API_CATEGORY_RESULT';
export const API_CATEGORY_ERROR = 'API_CATEGORY_ERROR';

//Newest
export const FETCH_NEWEST = 'FETCH_NEWEST';
export const REFRESH_NEWEST = 'REFRESH_NEWEST';
export const API_NEWEST_RESULT = 'API_NEWEST_RESULT';
export const API_NEWEST_ERROR = 'API_NEWEST_ERROR';

//Popular
export const FETCH_POPULAR = 'FETCH_POPULAR';
export const REFRESH_POPULAR = 'REFRESH_POPULAR';
export const API_POPULAR_RESULT = 'API_POPULAR_RESULT';
export const API_POPULAR_ERROR = 'API_POPULAR_ERROR';

//Article storage
export const ADD_ARTICLE_TO_HISTORY = 'ADD_ARTICLE_TO_HISTORY';
export const SAVE_ARTICLE = 'SAVE_ARTICLE';
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE';

//Navigation
export const FETCH_MENU_ITEMS = 'FETCH_MENU_ITEMS';
export const API_MENU_ITEMS_RESULT = 'API_MENU_ITEMS_RESULT';
export const API_MENU_ITEMS_ERROR = 'API_MENU_ITEMS_ERROR';

export const FETCH_PROGRAM = 'FETCH_PROGRAM';
export const API_PROGRAM_RESULT = 'API_PROGRAM_RESULT';
export const API_PROGRAM_ERROR = 'API_PROGRAM_ERROR';

export const SET_LAUNCH_URL = 'SET_LAUNCH_URL';
export const CLEAR_LAUNCH_URL = 'CLEAR_LAUNCH_URL';

//Settings
export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE';
export const SET_TEXT_SIZE_MULTIPLIER = 'SET_TEXT_SIZE_MULTIPLIER';
export const SET_IMAGE_SCALE_FACTOR = 'SET_IMAGE_SCALE_FACTOR';
export const SET_CONFIG = 'SET_CONFIG';
export const SET_FORECAST_LOCATION = 'SET_FORECAST_LOCATION';

export const OPEN_CATEGORY_FOR_NAME = 'OPEN_CATEGORY_FOR_NAME';
export const OPEN_CATEGORY_FOR_ID = 'OPEN_CATEGORY_FOR_ID';

export const SET_DAILY_QUESTION_CHOICE = 'SET_DAILY_QUESTION_CHOICE';
