//Home
export const FETCH_HOME = 'FETCH_HOME';
export const API_HOME_RESULT = 'API_HOME_RESULT';
export const API_HOME_ERROR = 'API_HOME_ERROR';

//Mediateka
export const FETCH_MEDIATEKA = 'FETCH_MEDIATEKA';
export const API_MEDIATEKA_RESULT = 'API_MEDIATEKA_RESULT';
export const API_MEDIATEKA_ERROR = 'API_MEDIATEKA_ERROR';

//Categories
export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const REFRESH_CATEGORY = 'REFRESH_CATEGORY';
export const API_CATEGORY_RESULT = 'API_CATEGORY_RESULT';
export const API_CATEGORY_ERROR = 'API_CATEGORY_ERROR';

//Newest
export const FETCH_NEWEST = 'FETCH_NEWEST';
export const REFRESH_NEWEST = 'REFRESH_NEWEST';
export const API_NEWEST_RESULT = 'API_NEWEST_RESULT';
export const API_NEWEST_ERROR = 'API_NEWEST_ERROR';

//Navigation
export const FETCH_MENU_ITEMS = 'FETCH_MENU_ITEMS';
export const API_MENU_ITEMS_RESULT = 'API_MENU_ITEMS_RESULT';
export const API_MENU_ITEMS_ERROR = 'API_MENU_ITEMS_ERROR';

export const FETCH_PROGRAM = 'FETCH_PROGRAM';
export const API_PROGRAM_RESULT = 'API_PROGRAM_RESULT';
export const API_PROGRAM_ERROR = 'API_PROGRAM_ERROR';

//Settings
export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE';
export const SET_TEXT_SIZE_MULTIPLIER = 'SET_TEXT_SIZE_MULTIPLIER';
export const SET_IMAGE_SCALE_FACTOR = 'SET_IMAGE_SCALE_FACTOR';
export const SET_CONFIG = 'SET_CONFIG';

export const OPEN_CATEGORY_FOR_NAME = 'OPEN_CATEGORY_FOR_NAME';
export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';

export const SET_SEARCH_FILTER = 'SET_SEARCH_FILTER';
export const RESET_SEARCH_FILTER = 'RESET_SEARCH_FILTER';
