name: Dummy Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        # with:
        #   path: mobile

      - name: Echo message
        run: echo "hello actions!"
